<a href="https://colab.research.google.com/github/peeka-boo0/ml-learning-journey/blob/main/notebooks/Day_1_Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practice Problems (Write these in your notebook)

Create a 2D array of shape (3, 4) with random integers from 1 to 50.

Slice the 2nd row.

Find mean, max, and standard deviation of your array.

Reshape it to (4, 3).

In [ ]:
import numpy as np


In [ ]:
a=np.random.randint(1,50, size=(3,4))
print(a)
print(a[:,1])
print(np.mean(a))
print(np.max(a))
print(np.std(a))
print(np.reshape(a,(4,3)))


[[ 3 33 18  9]
 [17 11 10 15]
 [25 21 41 25]]
[33 11 21]
19.0
41
10.319883720275147
[[ 3 33 18]
 [ 9 17 11]
 [10 15 25]
 [21 41 25]]
