<a href="https://colab.research.google.com/github/peeka-boo0/ml-learning-journey/blob/main/notebooks/Day_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import numpy

In [ ]:
import numpy as np

# The basics

In [ ]:
a = np.array([1,2,3], dtype='int16')   #for declirimg numpy we use np.array([the list])

print(a)

b= np.array([[1,2,3],[4,5,6]]) #for multi dimesion do list insde a list

print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
a.ndim
#.ndim give you the dims of the array

2

In [ ]:
a.shape



(2, 3)

In [ ]:


#for geting itemsize

a.itemsize

2

In [ ]:
#for total no of items

a.size



3

# **Accesing/Changing specifice row ,coloum ,element etc**

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#for geting an specific element from an array
a[1,5]

np.int64(13)

In [ ]:
#get a specific row

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#for geting all the column

a[:,2]

array([ 3, 10])

In [ ]:
# getting lill more fancy [stating:endindex:stepsize]

a[0,1:6:2]

array([2, 4, 6])

In [ ]:
a[1,5]=20

print(a)

a[:,2]=7
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  7  4  5  6  7]
 [ 8  9  7 11 12 20 14]]


In [ ]:
d=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(d)
d.shape

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


(3, 1, 3)

In [ ]:
d[2,0,0]

np.int64(7)

# **initializing different type of arrays**

In [ ]:
#all zero matrix

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#all 1s mateix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
#any other number

np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [ ]:
#for chaning an list the alrady exexting with a number (full_like)

np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#for a arry with random decimel number

np.random.rand(4,2)

array([[0.5002475 , 0.36274202],
       [0.65280433, 0.18578053],
       [0.2644568 , 0.43643019],
       [0.15430568, 0.99312721]])

In [ ]:
#for a arry with random integer values

np.random.randint(0,7,size=(3,3))


array([[5, 1, 1],
       [5, 0, 0],
       [5, 6, 2]])

In [ ]:
#for creating a identical arry
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#repiting array to creat a new ARRAY
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


# **Task 1**

In [ ]:
# f1=np.ones((5,5))
print(f1)
f2=np.zeros((3,3))
print(f2)
f2[1,1]=9
print(f2)
f1[1:4,1:4]=f2
print(f1)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# **copping an array **

In [ ]:
 a = np.array([1,2,3])

#b=a
'''the = will not assine the value of a to b
insted it will point the same data stored in memory
like this will store pointer address and any change
in b will gonna affect a'''

b=a.copy()
b[0]=100
print(a)
print(b)


[1 2 3]
[100   2   3]


# **Mathmatice**

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2


In [ ]:
a*2

In [ ]:
a / 2

In [ ]:
b =np.array([1,0,1,0])

a + b

array([2, 2, 4, 4])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
#taking trignometry values

np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# **lineaar algebra**

In [ ]:
a = np.array([[1,2],[3,4]])
print(a)

b = np.full((2,3),2)
print(b)

np.matmul(a,b)

[[1 2]
 [3 4]]
[[2 2 2]
 [2 2 2]]


array([[ 6,  6,  6],
       [14, 14, 14]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

# **statistice**

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)


np.int64(1)

In [ ]:
np.max(stats,axis=1)

array([3, 6])

In [ ]:
np.sum(stats)

np.int64(21)

# **Reorgeniging array**

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
#vertical stacking matrixex

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#horizental stacks
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# ***Miscellanous  ***

load data from file

In [ ]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[ 1  3  4  5  6  8  9 34  2  5 75 25 97 43  2  8 22 56 92]


# ***boolean masking and advance indexing***

In [ ]:
filedata [filedata > 50]

array([75, 97, 56, 92], dtype=int32)

In [ ]:
#you can index with a list in numpy

np.array([1,2,3,4,5,6,7,8,9])[[1,2,8]]

array([2, 3, 9])

In [ ]:
((filedata > 50 ) & (filedata < 100))

array([False, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False,  True,
        True])